# Generated by Django 5.0 on 2023-12-15 15:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('text_en', models.TextField(null=True)),
                ('text_ru', models.TextField(null=True)),
                ('text_uz', models.TextField(null=True)),
                ('answer_a', models.TextField()),
                ('answer_a_en', models.TextField(null=True)),
                ('answer_a_ru', models.TextField(null=True)),
                ('answer_a_uz', models.TextField(null=True)),
                ('answer_b', models.TextField()),
                ('answer_b_en', models.TextField(null=True)),
                ('answer_b_ru', models.TextField(null=True)),
                ('answer_b_uz', models.TextField(null=True)),
                ('answer_c', models.TextField()),
                ('answer_c_en', models.TextField(null=True)),
                ('answer_c_ru', models.TextField(null=True)),
                ('answer_c_uz', models.TextField(null=True)),
                ('answer_d', models.TextField()),
                ('answer_d_en', models.TextField(null=True)),
                ('answer_d_ru', models.TextField(null=True)),
                ('answer_d_uz', models.TextField(null=True)),
                ('answer', models.CharField(choices=[('answer_a', 'A variant'), ('answer_b', 'B variant'), ('answer_c', 'C variant'), ('answer_d', 'D variant')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Bajarilgan vaqt')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50, null=True)),
                ('name_ru', models.CharField(max_length=50, null=True)),
                ('name_uz', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150, null=True)),
                ('name_ru', models.CharField(max_length=150, null=True)),
                ('name_uz', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(blank=True, max_length=20, null=True)),
                ('is_True', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('title_en', models.CharField(max_length=50, null=True)),
                ('title_ru', models.CharField(max_length=50, null=True)),
                ('title_uz', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
